import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Poppins({
	subsets: ["latin"],
	weight: "600"
});

declare global {
	interface Window {
	  dataLayer?: any[];
	}
  }
  
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark sm:text-8xl text-4xl bg-background">
		  <Head>
			{/* Other meta tags and head elements */}
			<script async src="https://www.googletagmanager.com/gtag/js?id=AW-11448837278"></script>
			<script>
			  window.dataLayer = window.dataLayer || [];
			  function gtag() { window.dataLayer.push(arguments); }
			  gtag('js', new Date());
			  gtag('config', 'AW-11448837278');
			</script>
		  </Head>
		  <body className={inter.className}>
			{children}
		  </body>
		</html>
	  );
}
